application: tweet-2-rss
version: 1-9
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /feed/.*
  script: feedempty.app
  
- url: /twitter_connect
  script: twitter_connect.app
  
- url: /oauth_callback
  script: oauth_callback.app

- url: /builder
  script: builder.app

- url: /static
  static_dir: view/static
  
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /localcreate
  script: local_create_datastore.app
  
- url: /.*
  script: main.app
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
